### PR TITLE
feat: add lto

### PR DESCRIPTION
**Pull request by CrazyboyQCD**
Add lto to get optimization and reduce library size.

### CODE REVIEW

**Comment by tirithen** [comment]
Hi @CrazyboyQCD ! And thanks for the pull request!

I initially merged this request, but needed to revert this as I then found that these changes will not build with the lto feature enabled on linux without additional build dependencies. I still would love to get your changes into the main branch though as long as they are compatible with linux and macos that might not be using clang-cl.

I believe that plain clang should be enough at least on linux/macos. As I'm a linux developer maybe you can help me out around how common clang-cl is on windows. How commonly would clang-cl be available among windows developers compared to standard clang?

I have updated the ci actions on the main branch with multi platform setups now so that it easier to verify all platforms for as long as I have ci minutes left on my account.

If clang-cl contains critical features missing in clang, and if it is commonly installed on windows dev machines it seem to me that it might be an interesting option specifically for that target platform only `#[cfg(target_os = "windows")]`.

Another option would be to have a one `lto` feature that uses standard clang, and a separate specific `lto-clang-cl` feature for clang-cl.

What are your thoughts on this?

**Comment by CrazyboyQCD** [comment]
@tirithen Thanks for your reply, I followed the steps in the [book](https://doc.rust-lang.org/rustc/linker-plugin-lto.html) and found that it is suffcient to use `[cfg(target_env = "msvc")]` for clang-cl to enable `lto` on windows.

If you approve the option above I will reopen this.

**Comment by tirithen** [comment]
Thanks for the link! I read up there and searched for some more alternatives.

There also seem to be a MSVC with Link-Time Code Generation (LTCG) (for cl.exe) option that could maybe also work? But I suppose that is not helpful in case your project is already using clang-cl? I have less familiarity with the Microsoft compiler echo system so possibly that is not the best of ideas.

What I'm after is for users to be able to build the crate easily on all platforms without to much custom dependencies, the cc crate selects the available compiler automatically.

But I see the point that custom settings like LTO with clang-cl might be desirable for some builds. Having it as a feature as you suggested might be good as long as that comes with documentation on the requirements for that feature. And if called specifically `lto` it should probably work on linux/macos with cc crate out of the box as well as ideally with cc and optional compiler on windows as well.

Could `clang-cl` it maybe be auto detected in the case of `[cfg(target_env = "msvc")]` or would that become problematic for windows users using MSVC cl.exe? If so maybe the feature could be named something like `lto-clang-cl` instead.

Either way I would be happy to see your re-opened merge request with some fix to this. If you want to I could add a matching linux lto setup right after.

**Comment by CrazyboyQCD** [comment]
@tirithen 
> There also seem to be a MSVC with Link-Time Code Generation (LTCG) (for cl.exe) option that could maybe also work?

It is an arg for MSVC linker, which is not wanted. I tried to use [/GL](https://learn.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization?view=msvc-170) and it bloated to ~30MB.

And I found it does not need to add `config.toml` to enable `lto`, just to add `lto = true` in `cargo.toml` would work. 

I thought two ways are diffirent, and appearantly the book is deprecated and took me wrong.

I did some test on my `Windows 10` and found both ways have the same results:

| compiler         |        flag        | size(KB) |
| :--------------- | :----------------: | :------: |
| default          |                    |   5013   |
| gcc(14.1.0)      | -flto -fuse-ld=lld |   3111   |
| clang(18.1.7)    | -flto -fuse-ld=lld |   1463   |
| clang-cl(18.1.7) | -flto -fuse-ld=lld |   1181   |

`clang-cl` is the best on `msvc` target, I think it is worth to add it under `lto-clang-cl`-like feature. 
Since I did not find out how to enable `lto` on cl compiler, we should write some requirements in `README` to make sure there is at least a gcc or clang compiler.

**Comment by tirithen** [comment]
@CrazyboyQCD thanks for the investigation!

Sure lets go for a `lto-clang-cl` feature for now then to have something working.

And yes, the README should mention the need for gcc/clang even when that feature is not active and the need for clang-cl when it is active.

Anyhow I could to some documentation in the README afterwards, but I would need help with verifying the `lto-clang-cl` feature part as I do not have a Windows machine to run it on.

Also the CI tests needs to change slightly as testing with `--all-features` now would break for non Windows/clang-cl environments, and there need to be a new Windows + `--features lto-clang-cl` job that also installs clang-cl before the run.

Sounds like a good plan now. :-)

**Pull request merged**
